// Code generated by hertz generator.

package admin

import (
	"context"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/jinzhu/copier"
	"hertz-admin/biz/domain"
	logic "hertz-admin/biz/logic/admin"
	"hertz-admin/data"

	"github.com/cloudwego/hertz/pkg/app"
	"hertz-admin/api/model/admin"
	base "hertz-admin/api/model/base"
)

// CreateDictionary .
// @router /api/admin/dict/create [POST]
func CreateDictionary(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.DictionaryInfo
	resp := new(base.BaseResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	var DictInfo domain.DictionaryInfo
	err = copier.Copy(&DictInfo, &req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	err = logic.NewDictionary(data.Default()).Create(ctx, &DictInfo)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.StatusCode = base.StatusCode_Success
	resp.StatusMsg = "success"
	c.JSON(consts.StatusOK, resp)
}

// UpdateDictionary .
// @router /api/admin/dict/update [POST]
func UpdateDictionary(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.DictionaryInfo
	resp := new(base.BaseResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	var DictInfo domain.DictionaryInfo
	err = copier.Copy(&DictInfo, &req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	err = logic.NewDictionary(data.Default()).Update(ctx, &DictInfo)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.StatusCode = base.StatusCode_Success
	resp.StatusMsg = "success"
	c.JSON(consts.StatusOK, resp)
}

// DeleteDictionary .
// @router /api/admin/dict [DELETE]
func DeleteDictionary(ctx context.Context, c *app.RequestContext) {
	var err error
	var req base.IDReq
	resp := new(base.BaseResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	err = logic.NewDictionary(data.Default()).Delete(ctx, req.ID)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.StatusCode = base.StatusCode_Success
	resp.StatusMsg = "success"
	c.JSON(consts.StatusOK, resp)
}

// DictionaryList .
// @router /api/admin/dict/list [GET]
func DictionaryList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.DictionaryPageReq
	resp := new(admin.DictionaryListResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	var dictListReq domain.DictListReq
	err = copier.Copy(&dictListReq, &req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	// get dict list
	dictList, total, err := logic.NewDictionary(data.Default()).List(ctx, &dictListReq)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp.StatusCode = base.StatusCode_Success
	resp.StatusMsg = "success"
	resp.Data = &admin.DictionaryInfoList{
		Total: uint64(total),
		Data:  make([]*admin.DictionaryInfo, 0, len(dictList)),
	}
	for _, dict := range dictList {
		resp.Data.Data = append(resp.Data.Data, &admin.DictionaryInfo{
			ID:          dict.ID,
			Name:        dict.Name,
			Title:       dict.Title,
			Status:      dict.Status,
			Description: dict.Description,
			CreatedAt:   dict.CreatedAt,
			UpdatedAt:   dict.UpdatedAt,
		})
	}
	c.JSON(consts.StatusOK, resp)
}

// CreateDictionaryDetail .
// @router /api/admin/dict/detail/create [POST]
func CreateDictionaryDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.DictionaryDetail
	resp := new(base.BaseResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	var DictDetail domain.DictionaryDetail
	err = copier.Copy(&DictDetail, &req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	err = logic.NewDictionary(data.Default()).CreateDetail(ctx, &DictDetail)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.StatusCode = base.StatusCode_Success
	resp.StatusMsg = "success"
	c.JSON(consts.StatusOK, resp)
}

// UpdateDictionaryDetail .
// @router /api/admin/dict/detail/update [POST]
func UpdateDictionaryDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.DictionaryDetail
	resp := new(base.BaseResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	var DictDetail domain.DictionaryDetail
	err = copier.Copy(&DictDetail, &req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	err = logic.NewDictionary(data.Default()).UpdateDetail(ctx, &DictDetail)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.StatusCode = base.StatusCode_Success
	resp.StatusMsg = "success"
	c.JSON(consts.StatusOK, resp)
}

// DeleteDictionaryDetail .
// @router /api/admin/dict/detail [DELETE]
func DeleteDictionaryDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req base.IDReq
	resp := new(base.BaseResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	err = logic.NewDictionary(data.Default()).DeleteDetail(ctx, req.ID)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}

	resp.StatusCode = base.StatusCode_Success
	resp.StatusMsg = "success"
	c.JSON(consts.StatusOK, resp)
}

// DetailByDictionaryName .
// @router /api/admin/dict/detail/list [GET]
func DetailByDictionaryName(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.DictionaryDetailReq
	resp := new(admin.DictionaryDetailListResp)
	err = c.BindAndValidate(&req)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusBadRequest, resp)
		return
	}

	dictDetailList, total, err := logic.NewDictionary(data.Default()).DetailListByDictName(ctx, req.Name)
	if err != nil {
		resp.StatusCode = base.StatusCode_Fail
		resp.StatusMsg = err.Error()
		c.JSON(consts.StatusInternalServerError, resp)
		return
	}
	resp.StatusCode = base.StatusCode_Success
	resp.StatusMsg = "success"
	resp.Data = &admin.DictionaryDetailList{
		Total: total,
		Data:  make([]*admin.DictionaryDetail, 0, len(dictDetailList)),
	}
	for _, dictDetail := range dictDetailList {
		resp.Data.Data = append(resp.Data.Data, &admin.DictionaryDetail{
			ID:        dictDetail.ID,
			ParentID:  dictDetail.ParentID,
			Title:     dictDetail.Title,
			Status:    dictDetail.Status,
			Key:       dictDetail.Key,
			Value:     dictDetail.Value,
			CreatedAt: dictDetail.CreatedAt,
			UpdatedAt: dictDetail.UpdatedAt,
		})
	}
	c.JSON(consts.StatusOK, resp)
}
