// Code generated by hertz generator.

package admin

import (
	"formulago/biz/handler/middleware"
	"formulago/configs"
	"formulago/data"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _captchaMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _healthcheckMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _initDatabaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	// add jwt Auth middleware
	return []app.HandlerFunc{middleware.GetJWTMiddleware(configs.Data(), data.Default(), data.CasbinEnforcer()).MiddlewareFunc(),
		middleware.LogsMiddleware(data.Default()),
		middleware.ForbidOperation(configs.Data())}
}

func _roleByIdMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _api0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _api1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _api2Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dictMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detailByDictionaryNameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dictionaryListMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detail0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createDictionaryDetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateDictionaryDetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dict0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createDictionaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateDictionaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteLogsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getLogsListMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menu0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menuListMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _paramMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menuParamListByMenuIdMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menuByRoleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _param0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMenuParamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMenuParamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menu1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _providerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getProviderListMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _provider0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createProviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateProviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createRoleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateRoleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _role0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _roleListMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateRoleStatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateTokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _token0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tokenListMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateProfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userProfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateUserStatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _user0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changePasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createUserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userListMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userPermCodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateUserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauth0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauthCallbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauthLoginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _structToProtoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteStructTagMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteApiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiListMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createApiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateApiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createAuthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiAuthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateApiAuthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMenuAuthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _MenuAuthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMenuAuthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteDictionaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteDictionaryDetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMenuParamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteProviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteRoleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteTokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteUserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletestructtagMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _initdatabaseMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _structtoprotoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apilistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedictionaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletedictionarydetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _detailbydictionarynameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dictionarylistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdictionarydetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedictionarydetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menulistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemenuparamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menuparamlistbymenuidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menubyroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmenuparamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemenuparamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rolelistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updaterolestatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _rolebyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletetokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tokenlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateprofileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateapiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createauthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiauthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateapiauthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmenuauthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _menuauthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemenuauthorityMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createdictionaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatedictionaryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletelogsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getlogslistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createmenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemenuMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getproviderlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateproviderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateroleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatetokenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changepasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userpermcodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauthcallbackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _oauthloginMw() []app.HandlerFunc {
	// your code...
	return nil
}
